insert into session (id, name, description) values (1, 'Edgeblab', 'Operator');
insert into session (id, name, description) values (2, 'Skidoo', 'Mechanical Systems Engineer');
insert into session (id, name, description) values (3, 'Jaxspan', 'Editor');
insert into session (id, name, description) values (4, 'Vidoo', 'Web Designer II');
insert into session (id, name, description) values (5, 'Wordware', 'Geologist III');
insert into session (id, name, description) values (6, 'Eare', 'Staff Accountant IV');
insert into session (id, name, description) values (7, 'Bubblebox', 'Data Coordinator');
insert into session (id, name, description) values (8, 'Devpoint', 'Staff Accountant II');
insert into session (id, name, description) values (9, 'Topicblab', 'Nurse Practicioner');
insert into session (id, name, description) values (10, 'Bluezoom', 'Librarian');
insert into session (id, name, description) values (11, 'Muxo', 'Internal Auditor');
insert into session (id, name, description) values (12, 'Wikibox', 'VP Sales');
insert into session (id, name, description) values (13, 'Muxo', 'Data Coordinator');
insert into session (id, name, description) values (14, 'Zoomcast', 'Software Consultant');
insert into session (id, name, description) values (15, 'Feedfire', 'Business Systems Development Analyst');
insert into session (id, name, description) values (16, 'Wikizz', 'Marketing Assistant');
insert into session (id, name, description) values (17, 'Livepath', 'Software Consultant');
insert into session (id, name, description) values (18, 'Twitterbeat', 'Social Worker');
insert into session (id, name, description) values (19, 'Skinix', 'Physical Therapy Assistant');
insert into session (id, name, description) values (20, 'Babbleopia', 'Administrative Officer');
insert into session (id, name, description) values (21, 'Livetube', 'Operator');
insert into session (id, name, description) values (22, 'Eayo', 'Assistant Professor');
insert into session (id, name, description) values (23, 'Zoomzone', 'Account Coordinator');
insert into session (id, name, description) values (24, 'Vipe', 'Safety Technician I');
insert into session (id, name, description) values (25, 'Trudoo', 'Quality Control Specialist');
insert into session (id, name, description) values (26, 'Twitterbeat', 'Help Desk Operator');
insert into session (id, name, description) values (27, 'Feedmix', 'Director of Sales');
insert into session (id, name, description) values (28, 'Zoozzy', 'Safety Technician III');
insert into session (id, name, description) values (29, 'Quire', 'Tax Accountant');
insert into session (id, name, description) values (30, 'Jabbersphere', 'Office Assistant III');
insert into session (id, name, description) values (31, 'Mita', 'Research Associate');
insert into session (id, name, description) values (32, 'Podcat', 'Assistant Manager');
insert into session (id, name, description) values (33, 'Youspan', 'Office Assistant II');
insert into session (id, name, description) values (34, 'Midel', 'Paralegal');
insert into session (id, name, description) values (35, 'Browsedrive', 'Media Manager IV');
insert into session (id, name, description) values (36, 'Buzzster', 'Civil Engineer');
insert into session (id, name, description) values (37, 'Zoombeat', 'Speech Pathologist');
insert into session (id, name, description) values (38, 'Jabberstorm', 'Database Administrator IV');
insert into session (id, name, description) values (39, 'Kimia', 'Paralegal');
insert into session (id, name, description) values (40, 'Demivee', 'Operator');
insert into session (id, name, description) values (41, 'Tagpad', 'Project Manager');
insert into session (id, name, description) values (42, 'Topicstorm', 'Chief Design Engineer');
insert into session (id, name, description) values (43, 'Vidoo', 'Administrative Assistant III');
insert into session (id, name, description) values (44, 'Feedspan', 'Director of Sales');
insert into session (id, name, description) values (45, 'Mudo', 'Graphic Designer');
insert into session (id, name, description) values (46, 'Feedfish', 'Legal Assistant');
insert into session (id, name, description) values (47, 'Viva', 'Administrative Officer');
insert into session (id, name, description) values (48, 'Meedoo', 'VP Product Management');
insert into session (id, name, description) values (49, 'Youfeed', 'Sales Associate');
insert into session (id, name, description) values (50, 'Innojam', 'Compensation Analyst');
insert into session (id, name, description) values (51, 'Buzzshare', 'Environmental Specialist');
insert into session (id, name, description) values (52, 'Skiptube', 'Food Chemist');
insert into session (id, name, description) values (53, 'Zoomdog', 'Account Coordinator');
insert into session (id, name, description) values (54, 'Lazz', 'Recruiter');
insert into session (id, name, description) values (55, 'Eayo', 'Automation Specialist IV');
insert into session (id, name, description) values (56, 'Twinte', 'Quality Engineer');
insert into session (id, name, description) values (57, 'Trupe', 'Graphic Designer');
insert into session (id, name, description) values (58, 'Jabberbean', 'Clinical Specialist');
insert into session (id, name, description) values (59, 'Voolith', 'Occupational Therapist');
insert into session (id, name, description) values (60, 'Myworks', 'Nurse');
insert into session (id, name, description) values (61, 'Jabberbean', 'Senior Editor');
insert into session (id, name, description) values (62, 'Skalith', 'Product Engineer');
insert into session (id, name, description) values (63, 'Skajo', 'Account Coordinator');
insert into session (id, name, description) values (64, 'Jabbersphere', 'Social Worker');
insert into session (id, name, description) values (65, 'Devcast', 'Chief Design Engineer');
insert into session (id, name, description) values (66, 'Rhynoodle', 'Account Coordinator');
insert into session (id, name, description) values (67, 'Tazzy', 'Nuclear Power Engineer');
insert into session (id, name, description) values (68, 'Yoveo', 'Database Administrator III');
insert into session (id, name, description) values (69, 'Oloo', 'Geological Engineer');
insert into session (id, name, description) values (70, 'Agimba', 'Project Manager');
insert into session (id, name, description) values (71, 'Bubblemix', 'Account Representative III');
insert into session (id, name, description) values (72, 'Jaloo', 'Cost Accountant');
insert into session (id, name, description) values (73, 'Buzzshare', 'Data Coordinator');
insert into session (id, name, description) values (74, 'Demimbu', 'Automation Specialist III');
insert into session (id, name, description) values (75, 'Digitube', 'Community Outreach Specialist');
insert into session (id, name, description) values (76, 'Gigazoom', 'Social Worker');
insert into session (id, name, description) values (77, 'Skivee', 'Design Engineer');
insert into session (id, name, description) values (78, 'Topicstorm', 'Senior Quality Engineer');
insert into session (id, name, description) values (79, 'Kanoodle', 'Marketing Manager');
insert into session (id, name, description) values (80, 'Wordware', 'Senior Financial Analyst');
insert into session (id, name, description) values (81, 'Livepath', 'Systems Administrator IV');
insert into session (id, name, description) values (82, 'Zooxo', 'Legal Assistant');
insert into session (id, name, description) values (83, 'Gabspot', 'Information Systems Manager');
insert into session (id, name, description) values (84, 'Zazio', 'Physical Therapy Assistant');
insert into session (id, name, description) values (85, 'Yozio', 'Assistant Media Planner');
insert into session (id, name, description) values (86, 'Skiptube', 'Analyst Programmer');
insert into session (id, name, description) values (87, 'Babblestorm', 'Registered Nurse');
insert into session (id, name, description) values (88, 'Dynabox', 'Accounting Assistant III');
insert into session (id, name, description) values (89, 'Wordware', 'Graphic Designer');
insert into session (id, name, description) values (90, 'Yotz', 'Administrative Assistant I');
insert into session (id, name, description) values (91, 'Twitterbridge', 'Technical Writer');
insert into session (id, name, description) values (92, 'Flipopia', 'Statistician I');
insert into session (id, name, description) values (93, 'Mymm', 'Health Coach II');
insert into session (id, name, description) values (94, 'Muxo', 'Financial Analyst');
insert into session (id, name, description) values (95, 'Tekfly', 'Human Resources Assistant II');
insert into session (id, name, description) values (96, 'Edgeblab', 'Software Consultant');
insert into session (id, name, description) values (97, 'Zoomlounge', 'Assistant Media Planner');
insert into session (id, name, description) values (98, 'Photofeed', 'Community Outreach Specialist');
insert into session (id, name, description) values (99, 'Skalith', 'Staff Accountant II');
insert into session (id, name, description) values (100, 'Omba', 'Staff Accountant III');
